apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: kuangjianqiang/department:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database-name
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database-password
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database-user
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_host
            - name: MYSQL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql_port
                 
                  
    